name: Auto Update Subscribe Resource

on:
  schedule:
    - cron: '45 * * * *'  #UTC0 间隔1消失执行一次
  workflow_dispatch:       # 支持手动触发

permissions:
  contents: write  # 允许写入仓库内容

jobs:
  update-uri-sub:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出主仓库（包含 v2_sub, ssr_sub 和 脚本）
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 3. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4. 安装 Python 依赖
      - name: Install Dependencies
        run: |
          pip install requests pytz

      # 5. 运行更新脚本
      - name: Run Update Script
        run: |
          python update_subscribe.py

      # 6. 提交和推送更新到主仓库
      - name: Commit and Push Updates
        run: |		  
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"          
          git add .
          current_time=$(TZ=Asia/Shanghai date +"%m-%d %T");
          git commit -m "Auto-update $current_time" || echo "No changes to commit"          
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/HikerX/zhifan_subscribe.git
